### ISSUE TITLE
CCS data compatibility?

### ISSUE THREAD

**Issue by AnnaE-F** [zhuweix/MethyladenosineFinder#2]
Hello,

Thanks for developing the tool.

For the project I am working on, we only have the CCS reads from PacBio sequencing (the sequencing facility cannot provide the subreads).

If I understand correctly, you use CCS reads to filter subreads and then call the methylated Adenines on the subreads.

My question is the following: would it be possible to use your tool directly on CCS reads, and if so, how? 
I understand the pipeline does not work if giving directly the CCS reads to the function m6aworkflow (instead of Subreads).

Have a nice day!

**Comment by zhuweix** [comment]
Cheers,

Unfortunately, this tool cannot process CCS reads. This is because that this tools used ipdSummary tool from Pacbio SMRTtools command line tools, which only worked for subreads. CCS reads only contains the average IPD values, and lost the information such as variation between subreads, which decreased the accuracy of prediction. I will recommend using subreads if possible.
